desarrolladores/urls.py
from django.conf.urls import url
from .views import (
        ListaDesarrollador,
        DetalleDesarrolladorMarcado,
        DesarrolladorNuevo,
        DesarrolladoresDelete,
        DesarrolladoresUpdate,
        )



urlpatterns = [
    url(r'^$', ListaDesarrollador.as_view(),name='lista'),
    url(r'^NuevoDesarrollador/$', DesarrolladorNuevo,name='nuevo'),
    url(r'^Actualizar/(?P<pk>\d+)/$', DesarrolladoresUpdate.as_view(), name='actualizar'),
    url(r'^Eliminar/(?P<pk>\d+)/$', DesarrolladoresDelete.as_view(), name='eliminar'),
    url(r'^(?P<marcado>[\w-]+)/$', DetalleDesarrolladorMarcado.as_view(), name='detalle'),
]

ted/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views
from django.conf.urls.static import static
from .views import home_page, reportes, contact_page, about_page, login_page, register_page, lista_de_usuarios, AuthDetail,AuthDelete,AuthUpdate,lista_sweb,lista_pweb
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page,name='home'),
    url(r'^Reportes/$', reportes,name='reportes'),
    url(r'^contacto/$', contact_page,name='contacto'),
    url(r'^acercade/$', about_page,name='about'),
    url(r'^login/$', login_page,name='login'),
    url(r'^user_list/$', lista_de_usuarios,name='users'),
    url(r'^register/$', register_page,name='register'),
    url(r'^borrar/usuario/(?P<pk>\d+)', AuthDelete.as_view(), name='delete'),
    url(r'^usuario/(?P<pk>\d+)', AuthDetail.as_view(), name='detail'),
    url(r'^editar/usuario(?P<pk>\d+)', AuthUpdate.as_view(), name='edit'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^Paginas-Web/$', lista_pweb,name='lista_pweb'),
    url(r'^Sistemas-Web/$', lista_sweb,name='lista_sweb'),
    url(r'^plantillas/',include("plantillas.urls",namespace='plantillas')),
    url(r'^desarrolladores/',include("desarrolladores.urls",namespace='desarrolladores')),
    url(r'^reset/PasswordReset', password_reset, {'template_name':'resetpassword/password_reset_form.html','email_template_name':'resetpassword/password_reset_email.html'},name='password_reset'),
    url(r'^reset/PassordResetDone', password_reset_done, {'template_name':'resetpassword/password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name':'resetpassword/password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset/Done', password_reset_complete, {'template_name':'resetpassword/password_reset_complete.html'},name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

desarrolladores/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import random
import os
from django.db import models
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator
from django.urls import reverse


# Create your models here.
def get_filename_ext(filepath):
    nombre_base = os.path.basename(filepath)
    nombre, ext = os.path.splitext(nombre_base)
    return nombre, ext


def upload_image_path(instancia, nombrearchivo):
    # print(instancia)
    # print(nombrearchivo)
    nuevo_nombrearchivo = random.randint(1,3910209312)
    nombre, ext = get_filename_ext(nombrearchivo)
    nombrearchivo_final = '{nuevo_nombrearchivo}{ext}'.format(nuevo_nombrearchivo=nuevo_nombrearchivo,ext=ext)
    return "desarrolladores/{nuevo_nombrearchivo}/{nombrearchivo_final}".format(
            nuevo_nombrearchivo=nuevo_nombrearchivo,
            nombrearchivo_final=nombrearchivo_final
            )
#C.V


def upload_cv_path(instancia, nombrearchivo):
    # print(instancia)
    # print(nombrearchivo)
    nuevo_nombrearchivo = random.randint(1,3910209312)
    nombre, ext = get_filename_ext(nombrearchivo)
    nombrearchivo_final = '{nuevo_nombrearchivo}{ext}'.format(nuevo_nombrearchivo=nuevo_nombrearchivo,ext=ext)
    return "cvs/{nuevo_nombrearchivo}/{nombrearchivo_final}".format(
            nuevo_nombrearchivo=nuevo_nombrearchivo,
            nombrearchivo_final=nombrearchivo_final
            )

class DesarrolladorQuerySet(models.query.QuerySet):
    def activo(self):
        return self.filter(activo=True)

    def destacado(self):
        return self.filter(destacado=True, activo=True)

class ManejadorDesarrollador(models.Manager):
    def get_queryset(self):
        return DesarrolladorQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().activo()

    def destacado(self): # Desarrollador.objects.destacado()
        return self.get_queryset().destacado()

    def get_by_id(self,id):
        qs = self.get_queryset().filter(id=id) # Desarrollador.objects == self.get_queryset()
        if qs.count()==1:
            return qs.first()
        return None


class Desarrollador(models.Model):
    nombre      = models.CharField(max_length=120)
    marcado     = models.SlugField(blank=True, unique=True)
    cumpleanos  = models.DateField()
    imagen      = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    activo      = models.BooleanField(default=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    estudios    = models.CharField(blank=True, max_length=100)
    cv          = models.FileField(upload_to=upload_cv_path, null=True, blank=True)
    correo      = models.EmailField()
    destacado   = models.BooleanField(default=True)
    facebook    = models.URLField(blank=True)
    instagram   = models.URLField(blank=True)
    twiter      = models.URLField(blank=True)


    objects = ManejadorDesarrollador()
    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        # return "/desarrollador/{marcado}/".format(marcado=self.marcado)
        return reverse("desarrolladores:detalle", kwargs={"marcado": self.marcado})


def desarrollador_pre_guardado_recividor(sender, instance, *arg, **kwargs):
    if not instance.marcado:
        instance.marcado = unique_slug_generator(instance)

pre_save.connect(desarrollador_pre_guardado_recividor, sender=Desarrollador)

desarrolladores/forms.py
# This Python file uses the following encoding: utf-8
from django import forms
from .models import Desarrollador
from django.forms import ModelForm, Textarea, DateInput, TextInput, NumberInput, SelectDateWidget, CheckboxInput, Select

class DesarrolladorForm(forms.ModelForm):
    class Meta:
        model = Desarrollador
        fields = {'nombre','cumpleanos','imagen','estudios','cv','correo','facebook','instagram','twiter'}
        labels =    {'nombre':'Nombre',
                    'cumpleanos':'Cumpleaños',
                    'estudios':'Estudios',
					'correo':'E-Mail',
                    'facebook':'Facebook',
                    'instagram':'Instagram',
                    'twiter':'Twitter'}
        widgets = {
            'nombre': TextInput(attrs={
                'class':'form-control',
                'id': 'nombre',
                'name': 'nombre',
                'placeholder':'Nombre...'
                }),
            'cumpleanos': SelectDateWidget(attrs={
                'class':'form-control',
                'id': 'cumpleanos',
                'name': 'cumpleanos',
                'placeholder':'Cumpleaños...'
                }),
			'estuidos': TextInput(attrs={
                'class':'form-control',
                'id': 'estudios',
                'name': 'estudios',
                'placeholder':'Estudios...'
                }),
			'correo': TextInput(attrs={
                'class':'form-control',
                'id': 'correo',
                'name': 'correo',
                'placeholder':'E-Mail...'
                }),
            'facebook': TextInput(attrs={
                'class':'form-control',
                'id': 'facebook',
                'name': 'facebook',
                'placeholder':'Facebook...'
                }),
            'instagram': TextInput(attrs={
                'class':'form-control',
                'id': 'instagram',
                'name': 'instagram',
                'placeholder':'Instagram...'
                }),
            'twiter': TextInput(attrs={
                'class':'form-control',
                'id': 'twiter',
                'name': 'twiter',
                'placeholder':'Twitter...'
                }),

        }

desarrolladores/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import Http404,HttpResponse,HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404
from .models import Desarrollador
from .forms import DesarrolladorForm
from desarrolladores.models import Desarrollador
from django.template import loader
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import (
    UpdateView,
    DeleteView
)
# Create your views here.

class ListaDesarrolladorDestacada(ListView):
    template_name = "desarrollador/lista-destacado.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Desarrollador.objects.all().destacado()

class DetalleDesarrolladorDestacada(DetailView):
    queryset = Desarrollador.objects.all().destacado()
    template_name = "desarrollador/detalle-destacado.html"

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     return Desarrollador.objects.destacado()



class ListaDesarrollador(ListView):
    template_name = "desarrolladores/lista.html"

    # def get_context_data(self, *args, **kwargs):
    #     context = super(ListaDesarrollador,self).get_context_data(*args,**kwargs)
    #     print(context)
    #     return context
    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Desarrollador.objects.all()

def lista_desarrollador(request):
    queryset = Desarrollador.objects.all('nombre')
    context = {
        'qs':queryset
    }
    return render(request, "desarrolladores/lista.html", context)


class DetalleDesarrolladorMarcado(DetailView):
    queryset = Desarrollador.objects.all()
    template_name = "desarrolladores/detalle.html"

    def get_object(self, *args, **kwargs):
        request = self.request
        marcado = self.kwargs.get('marcado')
        # instancia = get_object_or_404(Desarrollador, marcado=marcado, activo=True)
        try:
            instancia = Desarrollador.objects.get(marcado=marcado, activo=True)
        except Desarrollador.DoesNotExist:
            raise Http404("No se encuentra...")
        except Desarrollador.MultipleObjectsReturned:
            qs = Desarrollador.objects.filter(marcado=marcado, activo=True)
            instancia = qs.first()
        except:
            raise Http404("¡Uhhmm")
        return instancia


class DetalleDesarrollador(DetailView):
    # queryset = Desarrollador.objects.all()
    template_name = "desarrolladores/detalle.html"

    def get_context_data(self, *args, **kwargs):
        context = super(DetalleDesarrollador,self).get_context_data(*args,**kwargs)
        print(context)
        # context = ['abc'] = 123
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        instancia = Desarrollador.objects.get_by_id(pk)
        if instancia is None:
            raise Http404("¡El Desarrollador que buscas no existe!")
        return instancia

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     pk = self.kwargs.get('pk')
    #     return queryset = Desarrollador.objects.filter(pk=pk)


def detalle_desarrollador(request, pk=None, *args, **kwargs):
    instancia = Desarrollador.objects.get(pk=pk, destacado=True)
    # instancia = get_object_or_404(Desarrollador, pk=pk, destacado=True)
    # try:
    #     instancia = Desarrollador.objects.get(pk=pk)
    # except Desarrollador.DoesNotExist:
    #     print("No hay Desarrolladores aqui.")
    #     raise Http404("¡El Plantilla que buscas no existe!")
    # except:
    #     print("¿Huh?")
    instancia = Desarrollador.objects.get_by_id(pk)
    if instancia is None:
        raise Http404("¡El Desarrollador que buscas no existe!")
    # print(instancia)
    # qs = Plantilla.objects.filter(id=pk)
    # # print(qs)
    # if qs.exists() and qs.count() == 1: # Longitud del qs
    #     instancia = qs.first()
    # else:
    #     raise Http404("¡La Plantilla que buscas no existe!")
    context = {
        'object':instancia
    }
    return render(request, "desarrolladores/detalle.html", context)

class DesarrolladoresUpdate(UpdateView):
    model = Desarrollador
    success_url = reverse_lazy('desarrolladores:lista')
    fields = ['nombre', 'marcado','cumpleanos','imagen', 'estudios','cv','correo', 'facebook', 'instagram', 'twiter']

class DesarrolladoresDelete(DeleteView):
    model = Desarrollador
    success_url = reverse_lazy('desarrolladores:lista')
    fields = ['nombre', 'marcado','cumpleanos','imagen', 'estudios','cv','correo', 'facebook', 'instagram', 'twiter']

def DesarrolladorNuevo(request):
    if request.method == 'POST':
        form = DesarrolladorForm(request.POST, request.FILES)
        if form.is_valid():
            desarrollador = form.save()
            desarrollador.save()
            return HttpResponseRedirect('/desarrolladores')
    else:
        form = DesarrolladorForm()
    template = loader.get_template('desarrolladores/desarrollador_nuevo.html')
    context = {
        'form': form
    }
    if request.user.is_authenticated():
        return HttpResponse(template.render(context, request))
    else:
        return HttpResponseRedirect('desarrolladores:lista')

templates/desarrolladores/desarrollador_confirm_delete.html
{% extends 'base.html' %}
{% block head_title %}| Eliminar Desarrollador{% endblock %}
{%load static%}
{% block content %}
{%load bootstrap4%}
{% url 'home' as home %}
{% url 'desarrolladores:lista' as lista %}
{% url 'desarrolladores:eliminar' as eliminar %}
<!-- START PAGE CONTENT -->
<div class="content">
  <div class="jumbotron" data-pages="parallax">
    <div class=" container-fluid container-fixed-lg sm-p-l-0 sm-p-r-0">
      <div class="inner">
        <!-- START BREADCRUMB -->
         <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{home}}">Home</a></li>
          <li class="breadcrumb-item"><a href="{{lista}}">Desarrolladores</a></li>
          <li class="breadcrumb-item active"><a href="{{eliminar}}">Eliminar {{object.nombre}}</a></li>
        </ol>
        <!-- END BREADCRUMB -->
      </div>
    </div>
  </div>
    <!-- START CONTAINER FLUID -->
    <div class="container-fluid container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <section class="section">
            <div class="container">
                <div class="row separatedv">
                  <form method="post">
                    {% csrf_token %}
                    <h1>¿Estás seguro que deseas borrar "{{ desarrollador.nombre }}</h1>
                    <button type="submit" name="submit" class="btn btn-danger">Borrar</button>
                  </form>
                </div>
            </div>
        </section>
        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->
</div>
<!-- END PAGE CONTENT -->
{% endblock %} {% include "footer.html" %}

templates/desarrolladores/desarrollador_nuevo.html
{% extends 'base.html' %}
{% block head_title %}| Nuevo Desarrollador{% endblock %}
{%load static%}
{%load bootstrap4%}
{% block content %}
{% url 'home' as home %}
{% url 'desarrolladores:listad' as listad %}
{% url 'desarrolladores:nuevad' as nuevad %}
      <!-- START PAGE CONTENT -->
      <div class="content">
        <div class="jumbotron" data-pages="parallax">
          <div class=" container-fluid container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner">
              <!-- START BREADCRUMB -->
               <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{home}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{listad}}">Desarrolladores</a></li>
                <li class="breadcrumb-item active"><a href="{{nuevad}}">Nuevo Desarrollador</a></li>
              </ol>
              <!-- END BREADCRUMB -->
            </div>
          </div>
        </div>
          <!-- START CONTAINER FLUID -->
          <div class="container-fluid container-fixed-lg">
              <!-- BEGIN PlACE PAGE CONTENT HERE -->
              <section class="section">
                  <div class="container">
                      <div class="row separatedv">
                          <div class="col-md-3"></div>
                          <div class="col-md-6">
                            <form enctype="multipart/form-data" method="post">
                              <div class="row">
                                {% csrf_token %}
                                <!-- {% bootstrap_form form %} -->
                                <div class="col-md-6">
                                  <div class="form-group">
                                    <label for="nombre">Nombre</label>
                                    <input type="text" name="nombre" name="nombre" title="" required id="nombre" maxlength="120" placeholder="Nombre..." class="form-control" />
                                  </div>
                                </div>
                                <div class="col-md-6">
                                  <div class="form-group"><label for="cumpleanos_day">Cumpleaños</label>
                                    <div class="row bootstrap4-multi-input">
                                      <div class="col-4"><select name="cumpleanos_day" name="cumpleanos" title="" required class="form-control" placeholder="" id="id_cumpleanos_day">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                        <option value="6">6</option>
                                        <option value="7">7</option>
                                        <option value="8">8</option>
                                        <option value="9">9</option>
                                        <option value="10">10</option>
                                        <option value="11">11</option>
                                        <option value="12">12</option>
                                        <option value="13">13</option>
                                        <option value="14">14</option>
                                        <option value="15">15</option>
                                        <option value="16">16</option>
                                        <option value="17">17</option>
                                        <option value="18">18</option>
                                        <option value="19">19</option>
                                        <option value="20">20</option>
                                        <option value="21">21</option>
                                        <option value="22">22</option>
                                        <option value="23">23</option>
                                        <option value="24">24</option>
                                        <option value="25">25</option>
                                        <option value="26">26</option>
                                        <option value="27">27</option>
                                        <option value="28">28</option>
                                        <option value="29">29</option>
                                        <option value="30">30</option>
                                        <option value="31">31</option>
                                      </select>
                                      </div>
                                      <div class="col-4">
                                        <select name="cumpleanos_month" name="cumpleanos" title="" required class="form-control" placeholder="" id="id_cumpleanos_month">
                                          <option value="1">Enero</option>
                                          <option value="2">Febrero</option>
                                          <option value="3">Marzo</option>
                                          <option value="4">Abril</option>
                                          <option value="5">Mayo</option>
                                          <option value="6">Junio</option>
                                          <option value="7">Julio</option>
                                          <option value="8">Agosto</option>
                                          <option value="9">Septiembre</option>
                                          <option value="10">Octubre</option>
                                          <option value="11">Noviembre</option>
                                          <option value="12">Diciembre</option>
                                        </select>
                                      </div>
                                      <div class="col-4">
                                        <select name="cumpleanos_year" name="cumpleanos" title="" required class="form-control" placeholder="" id="id_cumpleanos_year">
                                          <option value="1990">1990</option>
                                          <option value="1991">1991</option>
                                          <option value="1992">1992</option>
                                          <option value="1993">1993</option>
                                          <option value="1994">1994</option>
                                          <option value="1995">1995</option>
                                          <option value="1996">1996</option>
                                          <option value="1997">1997</option>
                                          <option value="1998">1998</option>
                                          <option value="1999">1999</option>
                                          <option value="2000">2000</option>
                                        </select>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div class="col-md-6">
                                  <div class="form-group">
                                    <label for="correo">E-Mail</label>
                                    <input type="text" name="correo" name="correo" title="" required id="correo" maxlength="254" placeholder="E-Mail..." class="form-control" />
                                  </div>
                                </div>
                                <div class="col-md-6">
                                  <div class="form-group">
                                    <label for="id_estudios">Estudios</label>
                                    <input type="text" name="estudios" title="" id="id_estudios" maxlength="100" placeholder="Estudios" class="form-control" />
                                  </div>
                                </div>
                                <div class="col-md-12">
                                  <div class="form-group">
                                    <label for="id_facebook">Facebook</label>
                                    <input type="text" name="facebook" title="" id="id_facebook" maxlength="100" placeholder="Facebook" class="form-control" />
                                  </div>
                                </div>
                                <div class="col-md-12">
                                  <div class="form-group">
                                    <label for="id_instagram">Instagram</label>
                                    <input type="text" name="instagram" title="" id="id_instagram" maxlength="100" placeholder="Instagram" class="form-control" />
                                  </div>
                                </div>
                                <div class="col-md-12">
                                  <div class="form-group">
                                    <label for="id_twiter">Twitter</label>
                                    <input type="text" name="twiter" title="" id="id_twiter" maxlength="100" placeholder="Twitter" class="form-control" />
                                  </div>
                                </div>
                                <div class="col-md-12">
                                  <div class="form-group">
                                    <label for="id_imagen">Imagen</label>
                                    <div class="row bootstrap4-multi-input">
                                      <div class="col-12">
                                        <input type="file" name="imagen" id="id_imagen" class="" title="" />
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div class="col-md-12">
                                  <div class="form-group">
                                    <label for="id_cv">Cv</label>
                                    <div class="row bootstrap4-multi-input">
                                      <div class="col-12">
                                        <input type="file" name="cv" id="id_cv" class="" title="" />
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div class="col-md-12 tex-right">
                                  <button type="submit" name="submit" class="btn btn-info">Hecho</button>
                                </div>
                              </div>
                            </form>
                          </div>
                          <div class="col-md-3">

                          </div>
                      </div>
                  </div>
              </section>
              <!-- END PLACE PAGE CONTENT HERE -->
          </div>
          <!-- END CONTAINER FLUID -->
      </div>
      <!-- END PAGE CONTENT -->
{% endblock %} {% include "footer.html" %}

templates/desarrolladores/lista.html
{% extends 'base.html' %}
{% block head_title %}| Desarolladores{% endblock %}
{%load static%}
{% block content %}
{% url 'home' as home %}
<!-- START PAGE CONTENT -->
<div class="content text-center">
  <div class="jumbotron" data-pages="parallax">
    <div class=" container-fluid container-fixed-lg sm-p-l-0 sm-p-r-0">
      <div class="inner">
        <!-- START BREADCRUMB -->
         <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{home}}">Home</a></li>
          <li class="breadcrumb-item active"><a href="{{listad}}">Desarrolladores</a></li>
        </ol>
        <!-- END BREADCRUMB -->
      </div>
    </div>
  </div>
  <h2>Desarrolladores</h2>
    <!-- START CONTAINER FLUID -->
    <div class="container-fluid container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <section class="section">
          <div class="container">
            <div class="row separatedv">
              {% for obj in object_list %}
              <div class="col-md-6">
                <!-- <h1 class="text-center">{{obj.nombre}}</h1> -->
                <aside class="profile-card">
              <header>
                <!-- here’s the avatar -->
                <a>
                  {% if obj.imagen %}
                  <img class="img-fluid" src="{{MEDIA_ROOT}}{{ obj.imagen.url }}" alt="img">
                  {% else %}
                  Sin imagen
                  {% endif %}
                </a>
                <!-- the username -->
                <h1>{{obj.nombre}}</h1>
                <h1>{{obj.estudios}}</h1>
                <!-- and role or location -->
              </header>
              <!-- bit of a bio; who are you? -->
              <div class="profile-bio conp text-center">
                <p class="conp">{{obj.cumpleanos}}</p>
                <p class="conp">{{obj.correo}}</p>
              </div>

              <!-- some social links to show off -->
              <div class="container">
                <div class="row">
                  <ul class="profile-social-links">
                    <!-- twitter - el clásico  -->
                    <li>
                      <a href="{{ obj.instagram }}" target="_blank">
                        <img src="https://images.vexels.com/media/users/3/137198/isolated/preview/07f0d7b69ef071571e4ada2f4d6a053a-icono-de-instagram-colorido-by-vexels.png">
                      </a>
                    </li>
                    <!-- envato – use this one to link to your marketplace profile -->
                    <li>
                      <a href="{{ obj.facebook }}" target="_blank">
                        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTikAUIOiej0vQMABZgiE0pfbXDVwNOs37gzSY_mCMBhaQUaJYJ">
                      </a>
                    </li>
                    <!-- codepen - your codepen profile-->
                    <li>
                      <a href="{{ obj.twiter }}" target="_blank">
                        <img src="https://tromber.es/wp-content/uploads/2018/02/twitter-sin-fondo.png">
                      </a>
                    </li>
                    <li>
                      <a>
                        {% if obj.cv %}
                        <a  href="{{ obj.cv.url }}" target="_blank">
                          <img data-toggle="tooltip2" data-html="true" title="C. V." src="https://image.flaticon.com/icons/png/512/504/504676.png">
                          <!-- <span class="tooltip">C.V</span> -->
                        </a>
                        {% else %}
                        {% endif %}
                      </a>
                    </li>
                    <li>
                      {% if user.is_authenticated %}
                      <a href="{% url 'desarrolladores:actualizar' obj.id %}">
                        <i class="fas fa-edit"></i>
                      </a>
                    <li>
                      <a class="rojo" href="{% url 'desarrolladores:eliminar' obj.id %}">
                        <i class="fas fa-trash"></i>
                      </a>
                    </li>
                      {%else %}
                      {%endif%}

                    <!-- add or remove social profiles as you see fit -->
                  </ul>

                </div>
              </div>
            </aside>
              </div>
              {% endfor %}
            </div>
          </div>
        </section>
        <!-- END PLACE PAGE CONTENT HERE -->
      </div>
      <!-- END CONTAINER FLUID -->
    </div>
    <!-- END PAGE CONTENT -->
{% endblock %}
{% include "footer.html" %}
<script type="text/javascript">
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>