desarrolladores/urls.py
from django.conf.urls import url
from .views import (
        ListaDesarrollador,
        DetalleDesarrolladorMarcado,
        DesarrolladorNuevo,
        DesarrolladoresDelete,
        DesarrolladoresUpdate,
        )



urlpatterns = [
    url(r'^$', ListaDesarrollador.as_view(),name='lista'),
    url(r'^NuevoDesarrollador/$', DesarrolladorNuevo,name='nuevo'),
    url(r'^Actualizar/(?P<pk>\d+)/$', DesarrolladoresUpdate.as_view(), name='actualizar'),
    url(r'^Eliminar/(?P<pk>\d+)/$', DesarrolladoresDelete.as_view(), name='eliminar'),
    url(r'^(?P<marcado>[\w-]+)/$', DetalleDesarrolladorMarcado.as_view(), name='detalle'),
]

plantillas/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import (
        ListaPlantilla,
        DetallePlantillaMarcado,
        PlantillaNueva,
        PlantillaUpdate,
        PlantillaDelete

        )



urlpatterns = [
    url(r'^$', ListaPlantilla.as_view(),name='lista'),
    url(r'^Nueva/',PlantillaNueva,name="nueva"),
    url(r'^(?P<marcado>[\w-]+)/$', DetallePlantillaMarcado.as_view(), name='detalle'),
    url(r'^Actualizar/(?P<pk>\d+)/$', PlantillaUpdate.as_view(), name='actualizar'),
    url(r'^Eliminar/(?P<pk>\d+)/$', PlantillaDelete.as_view(), name='eliminar'),
]

ted/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views
from django.conf.urls.static import static
from .views import home_page, reportes, contact_page, about_page, login_page, register_page, lista_de_usuarios, AuthDetail,AuthDelete,AuthUpdate,lista_sweb,lista_pweb
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page,name='home'),
    url(r'^Reportes/$', reportes,name='reportes'),
    url(r'^contacto/$', contact_page,name='contacto'),
    url(r'^acercade/$', about_page,name='about'),
    url(r'^login/$', login_page,name='login'),
    url(r'^user_list/$', lista_de_usuarios,name='users'),
    url(r'^register/$', register_page,name='register'),
    url(r'^borrar/usuario/(?P<pk>\d+)', AuthDelete.as_view(), name='delete'),
    url(r'^usuario/(?P<pk>\d+)', AuthDetail.as_view(), name='detail'),
    url(r'^editar/usuario(?P<pk>\d+)', AuthUpdate.as_view(), name='edit'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^Paginas-Web/$', lista_pweb,name='lista_pweb'),
    url(r'^Sistemas-Web/$', lista_sweb,name='lista_sweb'),
    url(r'^plantillas/',include("plantillas.urls",namespace='plantillas')),
    url(r'^desarrolladores/',include("desarrolladores.urls",namespace='desarrolladores')),
    url(r'^reset/PasswordReset', password_reset, {'template_name':'resetpassword/password_reset_form.html','email_template_name':'resetpassword/password_reset_email.html'},name='password_reset'),
    url(r'^reset/PassordResetDone', password_reset_done, {'template_name':'resetpassword/password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name':'resetpassword/password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset/Done', password_reset_complete, {'template_name':'resetpassword/password_reset_complete.html'},name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% include "head.html" %}
{% load static %}
<title>T. E. D.{% block head_title %}{% endblock %}</title>
<link rel="shortcut icon" href="{% static 'img/t.e.d.png' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
{% include "sidebar.html" %}

{% include "searchbar.html" %}

{% block content %}
{% endblock %}

{% include "footer.html" %}

templates/footer.html
{% load static %}
<!-- START FOOTER -->
<div class="container-fluid container-fixed-lg footer">
  <div class="copyright sm-text-center">
    <p class="small no-margin pull-left sm-pull-reset text-center">
      <i class="fab fa-js"></i>      <i class="fab fa-html5"></i>      <i class="fab fa-css3-alt"></i>      <i class="fas fa-terminal"></i>      <i class="fab fa-apple"></i>      <i class="fab fa-linux"></i>      <i class="fab fa-windows"></i>      <i class="fab fa-ubuntu"></i>      <i class="fab fa-python"></i>      <i class="fab fa-php"></i>      <i class="fas fa-database"></i>      <i class="fas fa-server"></i>      <i class="fab fa-node"></i>      <i class="fab fa-java"></i>      <i class="fab fa-angular"></i>      <i class="fab fa-raspberry-pi"></i>      <i class="fas fa-mobile-alt"></i>      <i class="fas fa-laptop"></i>      <i class="fas fa-desktop"></i>      <i class="fas fa-tablet-alt"></i>      <i class="fas fa-wifi"></i>
      <!-- <span class="hint-text">Copyright © 2018</span>
      <span class="font-montserrat">Credits by<a href="https://twitter.com/ChinozRamm" class="m-l-10 m-r-10">@Andre Ponce</a></span> -->
    </p>
    <div class="clearfix"></div>
  </div>
</div>
<!-- END FOOTER -->
</div>
<!-- END PAGE CONTENT WRAPPER -->
</div>
<!-- END PAGE CONTAINER -->
<!--START QUICKVIEW -->

{% include "quickview.html" %}
<!-- END QUICKVIEW -->
<!-- START OVERLAY -->


<!-- END OVERLAY -->
<!-- BEGIN VENDOR JS -->
<!-- BEGIN VENDOR JS -->
<!-- Dashboard -->
<script src="{% static 'dashbord/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashbord/js/Chart.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashbord/js/charts-home.js' %}" type="text/javascript"></script>
<script src="{% static 'dashbord/js/front.js' %}" type="text/javascript"></script>
<script src="{% static 'dashbord/js/grasp_mobile_progress_circle-1.0.0.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashbord/js/jquery.cookie.js' %}" type="text/javascript"></script>
<script src="{% static 'dashbord/js/jquery.mCustomScrollbar.concat.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashbord/js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashbord/js/jquery.validate.min.js' %}" type="text/javascript"></script>
<script src="{% static 'dashbord/js/popper.min.js' %}" type="text/javascript"></script>
<!-- Dashboard -->
<script src="{% static 'assets/plugins/pace/pace.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugins/jquery/jquery-1.11.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugins/modernizr.custom.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugins/jquery-ui/jquery-ui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugins/tether/js/tether.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugins/jquery/jquery-easy.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugins/jquery-unveil/jquery.unveil.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugins/jquery-bez/jquery.bez.min.js' %}"></script>
<script src="{% static 'assets/plugins/jquery-ios-list/jquery.ioslist.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/plugins/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'assets/plugins/jquery-actual/jquery.actual.min.js' %}"></script>
<script src="{% static 'assets/plugins/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/plugins/switchery/js/switchery.min.js' %}"></script>
<script src="{% static 'assets/plugins/jquery-inputmask/jquery.inputmask.min.js' %}" charset="utf-8" type="text/javascript"></script>
<script src="{% static 'js/jquery.mask.js' %}" charset="utf-8"></script>
<script src="{% static 'js/jquery.mask.min.js' %}" charset="utf-8"></script>
<!-- <script src="{% static 'js/custom.js' %}" charset="utf-8"></script> -->
<!-- END VENDOR JS -->
<!-- BEGIN CORE TEMPLATE JS -->
<script src="{% static 'pages/js/pages.js' %}" type="text/javascript"></script>
<script src="{% static 'js/loader.js' %}" type="text/javascript"></script>
<!-- END CORE TEMPLATE JS -->
<!-- BEGIN PAGE LEVEL JS -->
<script src="{% static 'assets/js/scripts.js' %}" type="text/javascript"></script>
<!-- <script src="{% static 'js/bars.js' %}" type="text/javascript"></script> -->
<script src="{% static 'js/home.js' %}" type="text/javascript"></script>
<script src="{% static 'js/particles.js' %}" type="text/javascript"></script>
<script src="{% static 'js/typing-text.js' %}" type="text/javascript"></script>
<script defer src="https://unpkg.com/imask"></script>
<!-- END PAGE LEVEL JS -->


</body>
</html>

templates/head.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>{% load static %}
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="apple-touch-icon" href="{% static 'img/icon.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/t.e.d.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/t.e.d.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/t.e.d.png' %}">
    <link rel="shortcut icon" href="{% static 'img/t.e.d.png' %}"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta name="description" content="Page Make With Django">
    <meta name="author" content="Carlo André Ponce Miranda, Luis Jesús Torres Nieves, Luis Emilio Piña Flores">
    <!-- Dashboard -->
    <link href="{% static 'assets/plugins/pace/pace-theme-flash.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/plugins/font-awesome/css/font-awesome.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/plugins/jquery-scrollbar/jquery.scrollbar.css' %}" rel="stylesheet" type="text/css" media="screen" />
    <link href="{% static 'assets/plugins/select2/css/select2.min.css' %}" rel="stylesheet" type="text/css" media="screen" />
    <link href="{% static 'assets/plugins/switchery/css/switchery.min.css' %}" rel="stylesheet" type="text/css" media="screen" />
    <link href="{% static 'pages/css/pages-icons.css' %}" rel="stylesheet" type="text/css">
    <link class="main-stylesheet" href="{% static 'pages/css/pages.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/plugins/simple-line-icons/simple-line-icons.css' %}" rel="stylesheet" type="text/css" media="screen"/>
    <link rel="stylesheet" href="{% static 'assets/plugins/switchery/css/switchery.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/switchery/css/switchery.css' %}">
    <link rel="stylesheet" href="{% static 'assets/plugins/switchery/css/switchery.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'css/bars.css' %}">
    <link rel="stylesheet" href="{% static 'css/loader.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'css/all.css' %}"> -->
    <!-- <script src="{% static 'js/bars.js' %}" charset="utf-8"></script> -->
    <script src="{% static 'assets/plugins/classie/classie.js' %}" type="text/javascript"></script>
  </head>
  <body class="fixed-header" onload="startTime()">

templates/home_page.html
{% extends 'base.html' %}
{% block head_title %}| Inicio{% endblock %}
{% load static %}
{% block content %}
{% url 'home' as home %}

<!-- LOADER SECTION -->
<div id="pageload">
  <div class="container-load">
    <img src="{% static 'img/t.e.d.png' %}" alt="">
  </div>
  <div class="data">
    <h1 data-text="Loading...">Loading...</h1>
    
  </div>
</div>
<!-- START PAGE CONTENT -->
<div class="content">
  <div class="jumbotron" data-pages="parallax">
    <div class=" container-fluid container-fixed-lg sm-p-l-0 sm-p-r-0">
      <div class="inner">
        <!-- START BREADCRUMB -->
        <ol class="breadcrumb">
          <li class="breadcrumb-item active"><a href="{{home}}">Home</a></li>
        </ol>
        <!-- END BREADCRUMB -->
      </div>
    </div>
  </div>
  <!-- START CONTAINER FLUID -->
  <div class="container-fluid container-fixed-lg">
    <!-- BEGIN PlACE PAGE CONTENT HERE -->
    <section class="section">
      <div class="container">
        <div class="row separatedv">
          <div class="col-md-2"></div>
          <div class="col-md-8">
            <div class="banner text-center">
              <div class="headline container-type">
                <pre class="text-success text-justify typing-text"></pre>
              </div>
            </div>
          </div>
          <div class="col-md-2"></div>
        </div>
        <div class="row separatedv">
          <div class="col-md-12">
            <h3 class="text-center">Páginas Web</h3>
          </div>
          <div class="col-md-2"></div>
          <div class="col-md-8">

            <div id="slider">
              <figure>
                {% for obje in pweb%}
                <img src="{{obje.imagen.url}}" alt="{{obje.imagen.url}}">
                {% endfor %}
              </figure>
            </div>
          </div>
          <div class="col-md-2"></div>
        </div>
        <div class="row separatedv">
          <div class="col-md-12">
            <h3 class="text-center">Sistemas Web</h3>
          </div>
        </div>
        {% for obje in sweb %}
        {% if obje.id == 3 %}
        <div class="row separatedv vara">
          <div class="col-md-6 abb">
            <img src="{{obje.imagen.url}}" alt="{{obje.imagen.url}}" class="img-fluid">
          </div>
          <div class="col-md-6 arr">
            <h4 class="text-center">{{obje.nombre}}</h4>
            <p class="text-center text-muted">Agregado hace {{obje.timestamp|timesince}}</p>
            <p class="text-center"><a class="text-darko" href="{{obje.get_absolute_url}}">
                Visitar
              </a></p>
          </div>
        </div>
        {% elif obje.id == 4 %}
        <div class="row separatedv varb">
          <div class="col-md-6 arr">
            <h4 class="text-center">{{obje.nombre}}</h4>
            <p class="text-center text-muted">Agregado hace {{obje.timestamp|timesince}}</p>
            <p class="text-center"><a class="text-darko" href="{{obje.get_absolute_url}}">
                Visitar
              </a></p>
          </div>
          <div class="col-md-6 abb">
            <img src="{{obje.imagen.url}}" alt="{{obje.imagen.url}}" class="img-fluid">
          </div>
        </div>
        {% elif obje.id == 10 %}
        <div class="row separatedv vara">
          <div class="col-md-6 abb">
            <img src="{{obje.imagen.url}}" alt="{{obje.imagen.url}}" class="img-fluid">
          </div>
          <div class="col-md-6 arr">
            <h4 class="text-center">{{obje.nombre}}</h4>
            <p class="text-center text-muted">Agregado hace {{obje.timestamp|timesince}}</p>
            <p class="text-center"><a class="text-darko" href="{{obje.get_absolute_url}}">
                Visitar
              </a></p>
          </div>
        </div>
        {% else %}
        <div class="row separatedv varb">
          <div class="col-md-6 arr">
            <h4 class="text-center">{{obje.nombre}}</h4>
            <p class="text-center text-muted">Agregado hace {{obje.timestamp|timesince}}</p>
            <p class="text-center"><a class="text-darko" href="{{obje.get_absolute_url}}">
                Visitar
              </a></p>
          </div>
          <div class="col-md-6 abb">
            <img src="{{obje.imagen.url}}" alt="{{obje.imagen.url}}" class="img-fluid">
          </div>
        </div>
        {% endif %}
        {% endfor %}

      </div>
    </section>
    <!-- END PLACE PAGE CONTENT HERE -->
  </div>
  <!-- END CONTAINER FLUID -->
</div>
<style media="screen">
  h4 {
    padding-top: 20px;
  }
</style>
<!-- END PAGE CONTENT -->
{% endblock %}
{% include "footer.html" %}

templates/searchbar.html
{% load static %}
<!-- START PAGE-CONTAINER -->
<div class="page-container" body onLoad="show5()">
  <!-- START PAGE HEADER WRAPPER -->
  <!-- START HEADER -->
  <div class="header ">
    <!-- START MOBILE SIDEBAR TOGGLE -->
    <a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-menu" data-toggle="sidebar">
    </a>
    <!-- END MOBILE SIDEBAR TOGGLE -->
    <div class="">
      <div class="brand inline">
        <a href="{% url 'home' %}">
          <img src="{% static 'img/t.e.d.png' %}" alt="logo" data-src="{% static 'img/t.e.d.png' %}" data-src-retina="{% static 'img/t.e.d.png' %}" height="50">
        </a>
      </div>
    </div>
    <div class="d-flex align-items-center">
        <p><a><span id="txt"></span></a></p>
    </div>
  </div>
  <!-- END HEADER -->
  <!-- END PAGE HEADER WRAPPER -->
  <!-- START PAGE CONTENT WRAPPER -->
  <div class="page-content-wrapper">

templates/sidebar.html
{% load static %}
{% url 'home' as home_url %}
{% url 'contacto' as contacto_url %}
{% url 'about' as about_url %}
{% url 'login' as login %}
{% url 'logout' as logout %}
{% url 'register' as register %}
{% url 'users' as users %}
{% url 'plantillas:lista' as lista %}
{% url 'plantillas:nueva' as nueva %}
{% url 'desarrolladores:lista' as listad %}
{% url 'desarrolladores:nuevo' as nuevod %}
{% url 'lista_pweb' as lista_pweb %}
{% url 'lista_sweb' as lista_sweb %}

<!-- BEGIN SIDEBAR -->
<!-- BEGIN SIDEBPANEL-->
<nav class="page-sidebar particles-js" data-pages="sidebar">
    <!-- BEGIN SIDEBAR MENU TOP TRAY CONTENT-->
    <div class="sidebar-overlay-slide from-top" id="appMenu">

    </div>
    <!-- END SIDEBAR MENU TOP TRAY CONTENT-->
    <!-- BEGIN SIDEBAR MENU HEADER-->
    <div class="sidebar-header text-center">
      <img src="{% static 'img/t.e.d.png' %}" alt="logo" class="brand" data-src="{% static 'img/t.e.d.png' %}" data-src-retina="{% static 'img/t.e.d.png' %}" height="50">
      <div class="sidebar-header-controls">

      </div>
    </div>
    <!-- END SIDEBAR MENU HEADER-->
    <!-- START SIDEBAR MENU -->
    <div class="sidebar-menu" style="padding-top:100px;">
        <!-- BEGIN SIDEBAR MENU ITEMS-->
        <ul class="menu-items">
          <li class="">
              <a href="{{home_url}}">
                  <span class="title">Inicio</span>
              </a>
              <span class="icon-thumbnail"><i class="fas fa-home"></i></span>
          </li>
            <li class="">
                <a href="javascript:;">
                    <span class="title">Plantillas</span>
                    <span class=" arrow"></span>
                </a>
                <span class="icon-thumbnail"><i class="fas fa-laptop-code"></i></span>
                <ul class="sub-menu">
                  {% if user.is_authenticated %}
                  <!-- <li class="">
                      <a class="linksidebar" href="{{lista}}">Lista</a>
                  </li> -->
                  <li class="">
                      <a class="linksidebar" href="{{nueva}}">Agregar Template</a>
                  </li>
                  {% else %}
                  {% endif %}
                  <li class="">
                      <a class="linksidebar" href="{{lista_pweb}}">Páginas Web</a>
                  </li>
                  <li class="">
                      <a class="linksidebar" href="{{lista_sweb}}">Sistemas Web</a>
                  </li>
                </ul>
            </li>
            <li class="">
                <a href="javascript:;">
                    <span class="title">Miembros</span>
                    <span class=" arrow"></span>
                </a>
                <span class="icon-thumbnail"><i class="fas fa-users"></i></span>
                <ul class="sub-menu">
                  {% if user.is_authenticated and user.is_superuser and user.is_staff%}
                  <li class="">
                      <a class="linksidebar" href="{{nuevod}}">Agregar Developer</a>
                  </li>
                  {% else %}
                  {% endif %}
                  <li class="">
                      <a class="linksidebar" href="{{listad}}">Lista</a>
                  </li>
                </ul>
            </li>
            <li class="">
                <a href="{{contacto_url}}">
                    <span class="title">Contacto</span>
                </a>
                <span class="icon-thumbnail"><i class="fas fa-mail-bulk"></i></span>
            </li>
            <li class="">
                <a href="{{about_url}}">
                    <span class="title">Acerca de</span>
                </a>
                <span class="icon-thumbnail"><i class="fas fa-scroll"></i></span>
            </li>
            <li class="">
                <a href="javascript:;">
                    <span class="title">Usuarios</span>
                    <span class=" arrow"></span>
                </a>
                <span class="icon-thumbnail"><i class="fas fa-user"></i></span>
                <ul class="sub-menu">
                    {% if user.is_authenticated %}
                    <li class="">
                        <a class="linksidebar" href="{{ logout }}">Cerrar Sesión</a>
                    </li>
                    {% if user.is_authenticated and user.is_staff and user.is_superuser %}
                    <li class="">
                        <a class="linksidebar" href="{{users}}">Lista de Usuarios</a>
                    </li>
                    {% else %} {% endif %} {% else %}
                    <li class="">
                        <a class="linksidebar" href="{{login}}">Inicias Sesión</a>
                    </li>
                    {% endif %}
                </ul>
            </li>
        </ul>
        <div class="clearfix"></div>
    </div>
    <!-- END SIDEBAR MENU -->
</nav>
<!-- END SIDEBAR -->
<!-- END SIDEBAR -->