plantillas/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import (
        ListaPlantilla,
        DetallePlantillaMarcado,
        PlantillaNueva,
        PlantillaUpdate,
        PlantillaDelete

        )



urlpatterns = [
    url(r'^$', ListaPlantilla.as_view(),name='lista'),
    url(r'^Nueva/',PlantillaNueva,name="nueva"),
    url(r'^(?P<marcado>[\w-]+)/$', DetallePlantillaMarcado.as_view(), name='detalle'),
    url(r'^Actualizar/(?P<pk>\d+)/$', PlantillaUpdate.as_view(), name='actualizar'),
    url(r'^Eliminar/(?P<pk>\d+)/$', PlantillaDelete.as_view(), name='eliminar'),
]

ted/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views
from django.conf.urls.static import static
from .views import home_page, reportes, contact_page, about_page, login_page, register_page, lista_de_usuarios, AuthDetail,AuthDelete,AuthUpdate,lista_sweb,lista_pweb
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page,name='home'),
    url(r'^Reportes/$', reportes,name='reportes'),
    url(r'^contacto/$', contact_page,name='contacto'),
    url(r'^acercade/$', about_page,name='about'),
    url(r'^login/$', login_page,name='login'),
    url(r'^user_list/$', lista_de_usuarios,name='users'),
    url(r'^register/$', register_page,name='register'),
    url(r'^borrar/usuario/(?P<pk>\d+)', AuthDelete.as_view(), name='delete'),
    url(r'^usuario/(?P<pk>\d+)', AuthDetail.as_view(), name='detail'),
    url(r'^editar/usuario(?P<pk>\d+)', AuthUpdate.as_view(), name='edit'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^Paginas-Web/$', lista_pweb,name='lista_pweb'),
    url(r'^Sistemas-Web/$', lista_sweb,name='lista_sweb'),
    url(r'^plantillas/',include("plantillas.urls",namespace='plantillas')),
    url(r'^desarrolladores/',include("desarrolladores.urls",namespace='desarrolladores')),
    url(r'^reset/PasswordReset', password_reset, {'template_name':'resetpassword/password_reset_form.html','email_template_name':'resetpassword/password_reset_email.html'},name='password_reset'),
    url(r'^reset/PassordResetDone', password_reset_done, {'template_name':'resetpassword/password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name':'resetpassword/password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset/Done', password_reset_complete, {'template_name':'resetpassword/password_reset_complete.html'},name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plantillas/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import random
import os
from django.db import models
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator
from django.urls import reverse


# Create your models here.
def get_filename_ext(filepath):
    nombre_base = os.path.basename(filepath)
    nombre, ext = os.path.splitext(nombre_base)
    return nombre, ext


def upload_image_path(instancia, nombrearchivo):
    # print(instancia)
    # print(nombrearchivo)
    nuevo_nombrearchivo = random.randint(1,3910209312)
    nombre, ext = get_filename_ext(nombrearchivo)
    nombrearchivo_final = '{nuevo_nombrearchivo}{ext}'.format(nuevo_nombrearchivo=nuevo_nombrearchivo,ext=ext)
    return "plantillas/{nuevo_nombrearchivo}/{nombrearchivo_final}".format(
            nuevo_nombrearchivo=nuevo_nombrearchivo,
            nombrearchivo_final=nombrearchivo_final
            )

class PlantillaQuerySet(models.query.QuerySet):
    def activo(self):
        return self.filter(activo=True)

    def destacado(self):
        return self.filter(destacado=True, activo=True)

class ManejadorPlantilla(models.Manager):
    def get_queryset(self):
        return PlantillaQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().activo()

    def destacado(self): # Plantilla.objects.destacado()
        return self.get_queryset().destacado()

    def get_by_id(self,id):
        qs = self.get_queryset().filter(id=id) # Plantilla.objects == self.get_queryset()
        if qs.count()==1:
            return qs.first()
        return None


class Plantilla(models.Model):
    nombre      = models.CharField(max_length=120)
    marcado     = models.SlugField(blank=True, unique=True)
    descripcion = models.TextField()
    imagen      = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    destacado   = models.BooleanField(default=True)
    activo      = models.BooleanField(default=True)
    categoria   = models.CharField(max_length=120,default='Páginas Web')
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = ManejadorPlantilla()
    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        # return "/plantilla/{marcado}/".format(marcado=self.marcado)
        return reverse("plantillas:detalle", kwargs={"marcado": self.marcado})


def plantilla_pre_guardado_recividor(sender, instance, *arg, **kwargs):
    if not instance.marcado:
        instance.marcado = unique_slug_generator(instance)

pre_save.connect(plantilla_pre_guardado_recividor, sender=Plantilla)

plantillas/forms.py
# This Python file uses the following encoding: utf-8
from django import forms
from .models import Plantilla
from django.forms import ModelForm, Textarea, DateInput, TextInput, NumberInput, SelectDateWidget, CheckboxInput, Select
categoria=(('---------','---------'),('Pagina Web','Pagina Web'),('Sistemas Web','Sistemas Web'))

class PlantillaForm(forms.ModelForm):
    class Meta:
        model = Plantilla
        fields = {'nombre','descripcion','categoria','imagen'}
        labels =    {'nombre':'Nombre',
                    'descripcion':'Descripción',
                    'class':'form-control',
                    'categoria':'Categoría'}
        widgets = {
            'nombre': TextInput(attrs={
                'class':'form-control',
                'id': 'nombre',
                'name': 'nombre',
                'placeholder':'Nombre...'
                }),
            'descripcion': TextInput(attrs={
                'class':'form-control',
                'id': 'descripcion',
                'name': 'descripcion',
                'placeholder':'Descripción...'
                }),
            'categoria': forms.Select(attrs={
                'id': 'categoria',
                'class':'form-control',
                'name': 'categoria',
                },choices=categoria),
        }

plantillas/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import Http404,HttpResponse,HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404
from .models import Plantilla
from .forms import PlantillaForm
from django.template import loader
from plantillas.models import Plantilla
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import (
    UpdateView,
    DeleteView,
    CreateView
)
# Create your views here.
def PlantillaNueva(request):
    if request.method == 'POST':
        form = PlantillaForm(request.POST, request.FILES)
        if form.is_valid():
            plantilla = form.save()
            plantilla.save()
            return HttpResponseRedirect('/plantillas')
    else:
        form = PlantillaForm()
    template = loader.get_template('plantillas/new_plantilla.html')
    context = {
        'form': form
    }
    if request.user.is_authenticated():
        return HttpResponse(template.render(context, request))
    else:
        return HttpResponseRedirect('productos:producto_list')


class ListaPlantillaDestacada(ListView):
    template_name = "plantillas/lista-destacado.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Plantilla.objects.all().destacado()

class DetallePlantillaDestacada(DetailView):
    queryset = Plantilla.objects.all().destacado()
    template_name = "plantillas/detalle-destacado.html"

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     return Plantilla.objects.destacado()



class ListaPlantilla(ListView):
    template_name = "plantillas/lista.html"

    # def get_context_data(self, *args, **kwargs):
    #     context = super(ListaPlantilla,self).get_context_data(*args,**kwargs)
    #     print(context)
    #     return context
    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Plantilla.objects.all()

def lista_plantilla(request):
    queryset = Plantilla.objects.all().order_by('nombre')
    context = {
        'qs':queryset
    }
    return render(request, "plantillas/lista.html", context)


class DetallePlantillaMarcado(DetailView):
    queryset = Plantilla.objects.all()
    template_name = "plantillas/detalle.html"

    def get_object(self, *args, **kwargs):
        request = self.request
        marcado = self.kwargs.get('marcado')
        # instancia = get_object_or_404(Plantilla, marcado=marcado, activo=True)
        try:
            instancia = Plantilla.objects.get(marcado=marcado, activo=True)
        except Plantilla.DoesNotExist:
            raise Http404("No se encuentra...")
        except Plantilla.MultipleObjectsReturned:
            qs = Plantilla.objects.filter(marcado=marcado, activo=True)
            instancia = qs.first()
        except:
            raise Http404("¡Uhhmm")
        return instancia


class DetallePlantilla(DetailView):
    # queryset = Plantilla.objects.all()
    template_name = "plantillas/detalle.html"

    def get_context_data(self, *args, **kwargs):
        context = super(DetallePlantilla,self).get_context_data(*args,**kwargs)
        print(context)
        # context = ['abc'] = 123
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        instancia = Plantilla.objects.get_by_id(pk)
        if instancia is None:
            raise Http404("¡La Plantilla que buscas no existe!")
        return instancia

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     pk = self.kwargs.get('pk')
    #     return queryset = Plantilla.objects.filter(pk=pk)


def detalle_plantilla(request, pk=None, *args, **kwargs):
    instancia = Plantilla.objects.get(pk=pk, destacado=True)
    # instancia = get_object_or_404(Plantilla, pk=pk, destacado=True)
    # try:
    #     instancia = Plantilla.objects.get(pk=pk)
    # except Plantilla.DoesNotExist:
    #     print("No hay Plantillas aqui.")
    #     raise Http404("¡El Plantilla que buscas no existe!")
    # except:
    #     print("¿Huh?")
    instancia = Plantilla.objects.get_by_id(pk)
    if instancia is None:
        raise Http404("¡La Plantilla que buscas no existe!")
    # print(instancia)
    # qs = Plantilla.objects.filter(id=pk)
    # # print(qs)
    # if qs.exists() and qs.count() == 1: # Longitud del qs
    #     instancia = qs.first()
    # else:
    #     raise Http404("¡La Plantilla que buscas no existe!")
    context = {
        'object':instancia
    }
    return render(request, "plantillas/detalle.html", context)

class PlantillaUpdate(UpdateView):
    model = Plantilla
    success_url = reverse_lazy('plantillas:lista')
    fields = ['nombre', 'marcado','descripcion','imagen', 'categoria']
class PlantillaDelete(DeleteView):
    model = Plantilla
    success_url = reverse_lazy('plantillas:lista')
    fields = ['nombre', 'marcado','descripcion','imagen', 'categoria']

templates/plantillas/detalle-destacado.html
{{ object.nombre }}<br>
{{ object.descripcion }}<br>
{{ object.precio }}<br>
{% if object.imagen %}
    <img src="{{ object.imagen.url }}" width="300">
{% endif %}

templates/plantillas/lista-destacado.html
{% extends 'base.html' %}
{% block head_title %}| Destacados{% endblock %}
{% block content %}
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="">Próximamente</h1>
    <p class="lead font-weight-normal">Siempre tenemos algo para ti...</p>
    <a class="btn btn-outline-secondary" href="#">Coming soon</a>
  </div>
  <div class="product-device box-shadow d-none d-md-block" style="width:200px; height:300px;"></div>
  <div class="product-device product-device-2 box-shadow d-none d-md-block" style="width:200px; height:300px;"></div>
</div>
{% for obj in object_list %}
  {% if obj.activo == True %}
  <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
    {% if obj.destacado == True %}
      <div class="bg-warning mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <div class="my-3 py-3">
          <h2 class="display-5">{{ obj.nombre }}</h2>
          <p class="lead">{{ obj.descripcion|truncatewords:12 }}</p>
          <a href="{{obj.get_absolute_url}}">
            <button type="button" name="button" class="btn btn-outline-danger">Ver</button>
          </a>
        </div>
        <div class="bg-light box-shadow mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;">
          {% if obj.imagen %}
          <img class="img-fluid" src="{{ obj.imagen.url }}" width="100%">
          {% endif %}<br>
        </div>
      </div>
        {% else %}
    {% endif %}
</div>
{% else %}
{% endif %}
{% endfor %}
{% endblock %}




<a href="{{ obj.get_absolute_url }}">{{ obj.nombre }}</a><br>

templates/plantillas/lista.html
{% extends 'base.html' %}
{% block head_title %}| Plantillas{% endblock %}
{%load static%}
{% block content %}
{% url 'home' as home %}
{% url 'plantillas:lista' as lista %}
<!-- START PAGE CONTENT -->
<div class="content">
  <div class="jumbotron" data-pages="parallax">
    <div class=" container-fluid container-fixed-lg sm-p-l-0 sm-p-r-0">
      <div class="inner">
        <!-- START BREADCRUMB -->
         <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{home}}">Home</a></li>
          <li class="breadcrumb-item active"><a href="{{lista}}">Plantillas</a></li>
        </ol>
        <!-- END BREADCRUMB -->
      </div>
    </div>
  </div>
    <!-- START CONTAINER FLUID -->
    <div class="container-fluid container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <section class="section">
          <div class="container">
            <div class="row separatedv">
              <div class="col-md-12">
                <h1 class="text-center">Plantillas</h1>
              </div>
              {% for obj in object_list %}
              <div class='col-xs-12 col-sm-6 col-md-4 glow'>
                <h4 class="text-center">{{obj.nombre}}</h4>
                <div class='csi-single-speaker'>
                  <figure>
                    <center>
                      {% if obj.imagen %}<img src='{{ obj.imagen.url }}' alt='speaker' class='glow' height='260'/>{% else %}Sin imagen{% endif %}
                    </center>
                    <figcaption>
                      <div class='speaker-info'>
                        <p class="text-light">{{obj.descripcion|truncatewords:5}}</p>
                        <sup class="text-light">{{obj.categoria}}</sup><br>
                        <a href="{{obj.get_absolute_url}}">
                          <button type="button" name="button" class="btn btn-info"><i class="far fa-eye"></i></button>
                        </a>
                        {% if user.is_authenticated %}
                        <a href="{% url "plantillas:actualizar" obj.id %}">
                          <button type="button" class="btn btn-warning">
                            <i class="fas fa-edit"></i>
                          </button>
                        </a>
                        <a href="{% url "plantillas:eliminar" obj.id %}">
                          <button type="button" class="btn btn-danger">
                            <i class="fa fa-eraser" aria-hidden="true"></i>
                          </button>
                        </a>
                        {%else %}
                        {%endif%}
                      </div>
                    </figcaption>
                  </figure>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </section>
        <!-- END PLACE PAGE CONTENT HERE -->
      </div>
      <!-- END CONTAINER FLUID -->
    </div>
    <!-- END PAGE CONTENT -->
{% endblock %}
{% include "footer.html" %}

templates/plantillas/new_plantilla.html
{% extends 'base.html' %}
{% block head_title %}| Nueva Plantilla{% endblock %}
{%load static%}
{%load bootstrap4%}
{% block content %}
{% url 'home' as home %}
{% url 'plantillas:lista' as lista %}
{% url 'plantillas:nueva' as nueva %}
<!-- START PAGE CONTENT -->
<div class="content">
  <div class="jumbotron" data-pages="parallax">
    <div class=" container-fluid container-fixed-lg sm-p-l-0 sm-p-r-0">
      <div class="inner">
        <!-- START BREADCRUMB -->
         <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{home}}">Home</a></li>
          <li class="breadcrumb-item"><a href="{{lista}}">Plantillas</a></li>
          <li class="breadcrumb-item active"><a href="{{nueva}}">Nueva Plantilla</a></li>
        </ol>
        <!-- END BREADCRUMB -->
      </div>
    </div>
  </div>
    <!-- START CONTAINER FLUID -->
    <div class="container-fluid container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <section class="section">
            <div class="container">
                <div class="row separatedv">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                      <h1 class="text-center">Agregar Nueva Plantilla</h1>
                      <form  enctype="multipart/form-data"method="POST">
                        <div class="row">
                          {% csrf_token %}
                          <!-- {% bootstrap_form form %} -->
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="nombre">Nombre</label>
                              <input type="text" name="nombre" name="nombre" title="" required id="nombre" maxlength="120" placeholder="Nombre..." class="form-control" />
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="categoria">Categoría</label>
                              <select name="categoria" name="categoria" title="" id="categoria" maxlength="120" class="form-control">
                                <option value="---------">---------</option>
                                <option value="Páginas Web">Páginas Web</option>
                                <option value="Sistemas Web">Sistemas Web</option>
                              </select>
                            </div>
                          </div>
                          <div class="col-md-12">
                            <div class="form-group">
                              <label for="descripcion">Descripción</label>
                              <input type="text" name="descripcion" name="descripcion" title="" required class="form-control" placeholder="" id="descripcion" />
                            </div>
                          </div>
                          <div class="col-md-12">
                            <div class="form-group">
                              <label for="id_imagen">Imagen</label>
                              <div class="row bootstrap4-multi-input">
                                <div class="col-12">
                                  <input type="file" name="imagen" id="id_imagen" class="" title="" />
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="col-md-12 tex-right">
                            <button type="submit" name="submit" class="btn btn-info">Completo</button>
                          </div>

                        </div>
                      </form>
                    </div>
                    <div class="col-md-3">

                    </div>
                </div>
            </div>
        </section>
        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->
</div>
<!-- END PAGE CONTENT -->
{% endblock %} {% include "footer.html" %}

templates/plantillas/plantilla_confirm_delete.html
{% extends 'base.html' %}
{% block head_title %}| Eliminar Plantilla{% endblock %}
{%load static%}
{% block content %}
{%load bootstrap4%}
{% url 'home' as home %}
{% url 'lista_pweb' as lista_pweb %}
{% url 'plantillas:eliminar' as eliminar %}
<!-- START PAGE CONTENT -->
<div class="content">
  <div class="jumbotron" data-pages="parallax">
    <div class=" container-fluid container-fixed-lg sm-p-l-0 sm-p-r-0">
      <div class="inner">
        <!-- START BREADCRUMB -->
         <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{home}}">Home</a></li>
          <li class="breadcrumb-item"><a href="{{lista_pweb}}">Páginas Web</a></li>
          <li class="breadcrumb-item active"><a href="{{eliminar}}">Eliminar {{object.nombre}}</a></li>
        </ol>
        <!-- END BREADCRUMB -->
      </div>
    </div>
  </div>
    <!-- START CONTAINER FLUID -->
    <div class="container-fluid container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <section class="section">
            <div class="container">
                <div class="row separatedv">
                  <form method="post">
                    {% csrf_token %}
                    <h1>¿Estás seguro que deseas borrar "{{ plantilla.nombre }}</h1>
                    <button type="submit" name="submit" class="btn btn-danger">Borrar</button>
                  </form>
                </div>
            </div>
        </section>
        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->
</div>
<!-- END PAGE CONTENT -->
{% endblock %} {% include "footer.html" %}

templates/plantillas/plantilla_form.html
{% extends 'base.html' %}
{% block head_title %}| Editar Plantilla{% endblock %}
{%load static%}
{%load bootstrap4%}
{% block content %}
{% url 'home' as home %}
{% url 'lista_pweb' as lista_pweb %}
{% url 'plantillas:actualizar' as actualizar %}
<!-- START PAGE CONTENT -->
<div class="content">
  <div class="jumbotron" data-pages="parallax">
    <div class=" container-fluid container-fixed-lg sm-p-l-0 sm-p-r-0">
      <div class="inner">
        <!-- START BREADCRUMB -->
         <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{home}}">Home</a></li>
          <li class="breadcrumb-item"><a href="{{lista_pweb}}">Páginas Web</a></li>
          <li class="breadcrumb-item active"><a href="{{actulizar}}">Editar Pagina Web</a></li>
        </ol>
        <!-- END BREADCRUMB -->
      </div>
    </div>
  </div>
    <!-- START CONTAINER FLUID -->
    <div class="container-fluid container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <section class="section">
            <div class="container">
                <div class="row separatedv">
                  <div class="col-md-3">

                  </div>
                  <div class="col-md-6">
                    <form enctype="multipart/form-data" method="post">
                      {% csrf_token %}
                      <!-- {% bootstrap_form form %} -->
                      <div class="form-group">
                        <label for="id_nombre">Nombre</label>
                        <input type="text" name="nombre" value="{{object.nombre}}" title="" required id="id_nombre" maxlength="120" placeholder="Nombre" class="form-control" />
                      </div>
                      <div class="form-group">
                        <label for="id_marcado">Marcado</label>
                        <input type="text" name="marcado" value="{{object.marcado}}" title="" id="id_marcado" maxlength="50" placeholder="Marcado" class="form-control" />
                      </div>
                      <div class="form-group">
                        <label for="id_descripcion">Descripcion</label>
                        <textarea name="descripcion" rows="10" title="" required cols="40" id="id_descripcion" placeholder="Descripcion" class="form-control">{{object.descripcion}}</textarea>
                      </div>
                      <div class="form-group">
                        <label for="id_imagen">Imagen</label>
                        <div class="row bootstrap4-multi-input"><div class="col-12"><input type="file" name="imagen" id="id_imagen" class="" title="" value="{%if object.imagen%}{{object.imagen.url}}{%else%}{%endif%}"/></div></div>
                      </div>
                      <div class="form-group">
                        <label for="id_categoria">Categoria</label>
                        <!-- <input type="text" name="categoria" title="" required id="id_categoria" maxlength="120" placeholder="Categoria" class="form-control" value="{{object.descripcion}}"/> -->
                        <select name="categoria" id="id_categoria" class="form-control">
                          <option value="{{object.categoria}}">{{object.categoria}}</option>
                          {%if object.categoria == 'Páginas Web'%}
                          <option value="Sistemas Web">Sistemas Web</option>
                          {%else%}
                          <option value="Páginas Web">Páginas Web</option>
                          {%endif%}
                        </select>
                      </div>
                      <button type="submit" name="submit" class="btn btn-success">Completo</button>
                    </form>
                  </div>
                  <div class="col-md-3">

                  </div>
                </div>
            </div>
        </section>
        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->
</div>
<!-- END PAGE CONTENT -->
{% endblock %} {% include "footer.html" %}

templates/plantillas/plantilla_nueva.html
{% extends 'base.html' %}
{% block head_title %}| Nueva Plantilla{% endblock %}
{%load static%}
{%load bootstrap4%}
{% block content %}
{% url 'home' as home %}
{% url 'plantillas:lista' as lista %}
{% url 'plantillas:nueva' as nueva %}
<!-- START PAGE CONTENT -->
<div class="content">
  <div class="jumbotron" data-pages="parallax">
    <div class=" container-fluid container-fixed-lg sm-p-l-0 sm-p-r-0">
      <div class="inner">
        <!-- START BREADCRUMB -->
         <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{home}}">Home</a></li>
          <li class="breadcrumb-item"><a href="{{lista}}">Plantillas</a></li>
          <li class="breadcrumb-item active"><a href="{{nueva}}">Nueva Plantilla</a></li>
        </ol>
        <!-- END BREADCRUMB -->
      </div>
    </div>
  </div>
    <!-- START CONTAINER FLUID -->
    <div class="container-fluid container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <section class="section">
            <div class="container">
                <div class="row separatedv">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                      <h1 class="text-center">Agregar Nueva Plantilla</h1>
                      <form method="post">
                        <div class="row">
                          {% csrf_token %}
                          <!-- {% bootstrap_form form %} -->
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="nombre">Nombre</label>
                              <input type="text" name="nombre" name="nombre" title="" required id="nombre" maxlength="120" placeholder="Nombre..." class="form-control" />
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="categoria">Categoría</label>
                              <select name="categoria" name="categoria" title="" id="categoria" maxlength="120" class="form-control">
                                <option value="---------">---------</option>
                                <option value="Páginas Web">Páginas Web</option>
                                <option value="Sistemas Web">Sistemas Web</option>
                              </select>
                            </div>
                          </div>
                          <div class="col-md-12">
                            <div class="form-group">
                              <label for="descripcion">Descripción</label>
                              <input type="text" name="descripcion" name="descripcion" title="" required class="form-control" placeholder="" id="descripcion" />
                            </div>
                          </div>
                          <div class="col-md-12">
                            <div class="form-group">
                              <label for="id_imagen">Imagen</label>
                              <div class="row bootstrap4-multi-input">
                                <div class="col-12">
                                  <input type="file" name="imagen" id="id_imagen" class="" title="" />
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="col-md-12 tex-right">
                            <button type="submit" name="submit" class="btn btn-info">Completo</button>
                          </div>

                        </div>
                      </form>
                    </div>
                    <div class="col-md-3">

                    </div>
                </div>
            </div>
        </section>
        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->
</div>
<!-- END PAGE CONTENT -->
{% endblock %} {% include "footer.html" %}